
enum
{
	ITEMHDLRLOADID_ViperArmor						= 2,
	ITEMHDLRLOADID_DestroyerArmor					= 0,
	ITEMHDLRLOADID_PhoenixRobe						= 2,
};

struct HeadModelStruct
{
	DWORD										dwCode;
	DWORD										dwTier;
	char										* pszFile;
};

static HeadModelStruct saFighterHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\tmh-b01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\tmh-b02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\tmh-b03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\tmh-b04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\tmh-b05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\tmh-b06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\tmh-b07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\tmh-b08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\tmh-b09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\tmh-b10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\tmh-b11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\tmh-b12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\tmh-b13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\tmh-b01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\tmh-b02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\tmh-b03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\tmh-b04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\tmh-b05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\tmh-b06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\tmh-b07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\tmh-b08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\tmh-b09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\tmh-b10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\tmh-b11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\tmh-b12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\tmh-b13a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\tmh_b01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\tmh_b02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\tmh_b03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\tmh_b04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\tmh_b05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\tmh_b06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\tmh_b07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\tmh_b08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\tmh_b09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\tmh_b10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\tmh_b11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\tmh_b12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\tmh_b13b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\tmh-b01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\tmh-b02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\tmh-b03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\tmh-b04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\tmh-b05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\tmh-b06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\tmh-b07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\tmh-b08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\tmh-b09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\tmh-b10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\tmh-b11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\tmh-b12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\tmh-b13c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\tmh-b01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\tmh-b02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\tmh-b03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\tmh-b04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\tmh-b05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\tmh-b06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\tmh-b07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\tmh-b08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\tmh-b09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\tmh-b10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\tmh-b11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\tmh-b12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\tmh-b13d.inf" },

	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tmh-b19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tmh-b20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tmh-b21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tmh-b22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tmh-b23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hfighter_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hfighter_03.inf" },


	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tmh-B25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Tmh-B25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tmh-B99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TmhB-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\TmhB-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\fsxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\fsxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TmhB14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TmhB15t.inf" },
	{ ITEMID_BigHeadValentine, 0,"char\\tmABCD\\TmhB15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TmhB16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TmhB17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TmhB30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TmhB31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TmhB32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaFS.inf" },
};

static HeadModelStruct saMechanicianHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\tmh-a01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\tmh-a02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\tmh-a03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\tmh-a04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\tmh-a05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\tmh-a06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\tmh-a07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\tmh-a08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\tmh-a09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\tmh-a10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\tmh-a11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\tmh-a12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\tmh-a13.inf" },
												
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\tmh-a01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\tmh-a02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\tmh-a03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\tmh-a04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\tmh-a05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\tmh-a06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\tmh-a07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\tmh-a08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\tmh-a09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\tmh-a10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\tmh-a11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\tmh-a12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\tmh-a13a.inf" },
												
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\tmh_a01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\tmh_a02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\tmh_a03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\tmh_a04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\tmh_a05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\tmh_a06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\tmh_a07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\tmh_a08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\tmh_a09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\tmh_a10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\tmh_a11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\tmh_a12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\tmh_a13b.inf" },
												
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\tmh-a01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\tmh-a02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\tmh-a03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\tmh-a04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\tmh-a05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\tmh-a06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\tmh-a07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\tmh-a08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\tmh-a09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\tmh-a10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\tmh-a11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\tmh-a12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\tmh-a13c.inf" },
												
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\tmh-a01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\tmh-a02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\tmh-a03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\tmh-a04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\tmh-a05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\tmh-a06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\tmh-a07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\tmh-a08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\tmh-a09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\tmh-a10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\tmh-a11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\tmh-a12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\tmh-a13d.inf" },


	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tmh-a19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tmh-a20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tmh-a21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tmh-a22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tmh-a23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hmech_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hmech_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tmh-A25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Tmh-A25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tmh-A99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TmhA-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\TmhA-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\msxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\msxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TmhA14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TmhA15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\TmhA15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TmhA16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TmhA17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TmhA30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TmhA31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TmhA32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaMS.inf" },

};

static HeadModelStruct saArcherHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\tfh-d01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\tfh-d02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\tfh-d03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\tfh-d04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\tfh-d05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\tfh-d06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\tfh-d07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\tfh-d08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\tfh-d09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\tfh-d10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\tfh-d11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\tfh-d12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\tfh-d13.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\tfh-d01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\tfh-d02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\tfh-d03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\tfh-d04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\tfh-d05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\tfh-d06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\tfh-d07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\tfh-d08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\tfh-d09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\tfh-d10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\tfh-d11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\tfh-d12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\tfh-d13a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\tfh_d01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\tfh_d02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\tfh_d03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\tfh_d04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\tfh_d05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\tfh_d06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\tfh_d07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\tfh_d08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\tfh_d09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\tfh_d10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\tfh_d11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\tfh_d12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\tfh_d13b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\tfh-d01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\tfh-d02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\tfh-d03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\tfh-d04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\tfh-d05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\tfh-d06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\tfh-d07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\tfh-d08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\tfh-d09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\tfh-d10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\tfh-d11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\tfh-d12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\tfh-d13c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\tfh-d01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\tfh-d02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\tfh-d03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\tfh-d04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\tfh-d05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\tfh-d06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\tfh-d07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\tfh-d08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\tfh-d09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\tfh-d10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\tfh-d11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\tfh-d12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\tfh-d13d.inf" },


	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tfh-d19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tfh-d20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tfh-d21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tfh-d22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tfh-d23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\harcher_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\harcher_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tfh-D25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Tfh-D25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tfh-D99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TfhD-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\TfhD-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\asxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\asxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TfhD14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TfhD15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\TfhD15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TfhD16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TfhD17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TfhD30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TfhD31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TfhD32.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nAS.inf" },

};

static HeadModelStruct saPikemanHeadModel[]
{ 
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\tmh-c01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\tmh-c02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\tmh-c03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\tmh-c04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\tmh-c05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\tmh-c06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\tmh-c07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\tmh-c08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\tmh-c09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\tmh-c10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\tmh-c11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\tmh-c12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\tmh-c13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\tmh-c01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\tmh-c02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\tmh-c03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\tmh-c04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\tmh-c05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\tmh-c06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\tmh-c07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\tmh-c08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\tmh-c09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\tmh-c10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\tmh-c11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\tmh-c12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\tmh-c13a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\tmh_c01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\tmh_c02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\tmh_c03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\tmh_c04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\tmh_c05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\tmh_c06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\tmh_c07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\tmh_c08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\tmh_c09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\tmh_c10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\tmh_c11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\tmh_c12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\tmh_c13b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\tmhC-01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\tmhC-02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\tmhC-03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\tmhC-04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\tmhC-05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\tmhC-06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\tmhC-07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\tmhC-08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\tmhC-09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\tmhC-10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\tmhC-11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\tmhC-12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\tmhC-13c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\tmh-c01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\tmh-c02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\tmh-c03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\tmh-c04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\tmh-c05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\tmh-c06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\tmh-c07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\tmh-c08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\tmh-c09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\tmh-c10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\tmh-c11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\tmh-c12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\tmh-c13d.inf" },


	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tmh-c19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tmh-c20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tmh-c21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tmh-c22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tmh-c23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hpike_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hpike_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tmh-C25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Tmh-C25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tmh-C99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TmhC-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\TmhC-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\psxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\psxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TmhC14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TmhC15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\TmhC15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TmhC16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TmhC17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TmhC30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TmhC31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TmhC32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaPS.inf" },

};

static HeadModelStruct saAtalantaHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\mfh-b01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\mfh-b02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\mfh-b03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\mfh-b04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\mfh-b05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\mfh-b06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\mfh-b07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\mfh-b08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\mfh-b09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\mfh-b10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\mfh-b11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\mfh-b12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\mfh-b13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\mfh-b01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\mfh-b02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\mfh-b03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\mfh-b04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\mfh-b05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\mfh-b06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\mfh-b07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\mfh-b08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\mfh-b09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\mfh-b10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\mfh-b11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\mfh-b12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\mfh-b13a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\mfh_b01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\mfh_b02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\mfh_b03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\mfh_b04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\mfh_b05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\mfh_b06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\mfh_b07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\mfh_b08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\mfh_b09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\mfh_b10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\mfh_b11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\mfh_b12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\mfh_b13b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\mfh-b01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\mfh-b02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\mfh-b03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\mfh-b04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\mfh-b05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\mfh-b06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\mfh-b07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\mfh-b08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\mfh-b09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\mfh-b10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\mfh-b11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\mfh-b12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\mfh-b13c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\mfh-b01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\mfh-b02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\mfh-b03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\mfh-b04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\mfh-b05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\mfh-b06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\mfh-b07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\mfh-b08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\mfh-b09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\mfh-b10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\mfh-b11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\mfh-b12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\mfh-b13d.inf" },

	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mfh-b19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mfh-b20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mfh-b21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mfh-b22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mfh-b23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hatalanta_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hatalanta_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mfh-B25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Mfh-B25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mfh-B99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MfhB-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\MfhB-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\ataxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\ataxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MfhB14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MfhB15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\MfhB15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MfhB16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MfhB17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MfhB30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MfhB31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MfhB32.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nATA.inf" },

};

static HeadModelStruct saKnightHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\mmh-a01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\mmh-a02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\mmh-a03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\mmh-a04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\mmh-a05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\mmh-a06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\mmh-a07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\mmh-a08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\mmh-a09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\mmh-a10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\mmh-a11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\mmh-a12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\mmh-a13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\mmh-a01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\mmh-a02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\mmh-a03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\mmh-a04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\mmh-a05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\mmh-a06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\mmh-a07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\mmh-a08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\mmh-a09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\mmh-a10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\mmh-a11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\mmh-a12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\mmh-a13a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\mmh_a01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\mmh_a02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\mmh_a03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\mmh_a04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\mmh_a05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\mmh_a06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\mmh_a07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\mmh_a08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\mmh_a09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\mmh_a10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\mmh_a11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\mmh_a12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\mmh_a13b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\mmh-a01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\mmh-a02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\mmh-a03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\mmh-a04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\mmh-a05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\mmh-a06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\mmh-a07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\mmh-a08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\mmh-a09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\mmh-a10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\mmh-a11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\mmh-a12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\mmh-a13c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\mmh-a01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\mmh-a02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\mmh-a03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\mmh-a04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\mmh-a05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\mmh-a06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\mmh-a07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\mmh-a08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\mmh-a09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\mmh-a10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\mmh-a11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\mmh-a12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\mmh-a13d.inf" },

	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mmh-a19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mmh-a20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mmh-a21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mmh-a22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mmh-a23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hknight_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hknight_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mmh-A25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Mmh-A25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mmh-A99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MmhA-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\MmhA-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\ksxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\ksxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MmhA14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MmhA15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\MmhA15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MmhA16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MmhA17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MmhA30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MmhA31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MmhA32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaKS.inf" },
};

static HeadModelStruct saMagicianHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\mmh-d01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\mmh-d02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\mmh-d03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\mmh-d04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\mmh-d05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\mmh-d06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\mmh-d07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\mmh-d08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\mmh-d09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\mmh-d10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\mmh-d11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\mmh-d12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\mmh-d13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\mmh-d01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\mmh-d02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\mmh-d03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\mmh-d04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\mmh-d05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\mmh-d06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\mmh-d07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\mmh-d08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\mmh-d09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\mmh-d10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\mmh-d11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\mmh-d12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\mmh-d13a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\mmh_d01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\mmh_d02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\mmh_d03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\mmh_d04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\mmh_d05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\mmh_d06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\mmh_d07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\mmh_d08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\mmh_d09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\mmh_d10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\mmh_d11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\mmh_d12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\mmh_d13b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\mmh-d01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\mmh-d02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\mmh-d03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\mmh-d04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\mmh-d05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\mmh-d06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\mmh-d07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\mmh-d08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\mmh-d09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\mmh-d10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\mmh-d11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\mmh-d12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\mmh-d13c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\mmh-d01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\mmh-d02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\mmh-d03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\mmh-d04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\mmh-d05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\mmh-d06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\mmh-d07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\mmh-d08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\mmh-d09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\mmh-d10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\mmh-d11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\mmh-d12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\mmh-d13d.inf" },

	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mmh-d19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mmh-d20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mmh-d21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mmh-d22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mmh-d23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hmage_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hmage_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mmh-D25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Mmh-D25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mmh-D99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MmhD-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\MmhD-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\mgxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\mgxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MmhD14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MmhD15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\MmhD15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MmhD16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MmhD17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MmhD30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MmhD31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MmhD32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaMG.inf" },

};

static HeadModelStruct saPriestessHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\mfh-c01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\mfh-c02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\mfh-c03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\mfh-c04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\mfh-c05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\mfh-c06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\mfh-c07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\mfh-c08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\mfh-c09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\mfh-c10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\mfh-c11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\mfh-c12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\mfh-c13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\mfh-c01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\mfh-c02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\mfh-c03a.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\mfh-c04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\mfh-c05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\mfh-c06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\mfh-c07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\mfh-c08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\mfh-c09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\mfh-c10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\mfh-c11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\mfh-c12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\mfh-c13a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\mfh_c01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\mfh_c02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\mfh_c03b.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\mfh_c04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\mfh_c05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\mfh_c06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\mfh_c07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\mfh_c08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\mfh_c09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\mfh_c10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\mfh_c11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\mfh_c12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\mfh_c13b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\mfh-c01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\mfh-c02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\mfh-c03c.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\mfh-c04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\mfh-c05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\mfh-c06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\mfh-c07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\mfh-c08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\mfh-c09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\mfh-c10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\mfh-c11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\mfh-c12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\mfh-c13c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\mfh-c01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\mfh-c02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\mfh-c03d.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\mfh-c04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\mfh-c05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\mfh-c06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\mfh-c07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\mfh-c08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\mfh-c09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\mfh-c10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\mfh-c11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\mfh-c12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\mfh-c13d.inf" },

	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mfh-c19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mfh-c20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mfh-c21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mfh-c22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mfh-c23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hpriestess_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hpriestess_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mfh-C25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Mfh-C25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mfh-C99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MfhC-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\MfhC-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\prsxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\prsxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MfhC14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MfhC15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\MfhC15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MfhC16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MfhC17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MfhC30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MfhC31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MfhC32.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nPRS.inf" },

};

static HeadModelStruct saAssassinHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\tfh-e01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\tfh-e02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\tfh-e03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\tfh-e04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\tfh-e05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\tfh-e06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\tfh-e07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\tfh-e08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\tfh-e09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\tfh-e10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\tfh-e11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\tfh-e12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\tfh-e13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\tfh-e01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\tfh-e02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\tfh-e03a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\tfh_e01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\tfh_e02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\tfh_e03b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\tfh-e01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\tfh-e02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\tfh-e03c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\tfh-e01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\tfh-e02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\tfh-e03d.inf" },

	/*
	
	Don't have these tier hair crown models for Assassin
	
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\tfh-e04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\tfh-e05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\tfh-e06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\tfh-e07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\tfh-e08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\tfh-e09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\tfh-e10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\tfh-e11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\tfh-e12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\tfh-e13a.inf" },
	
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\tfh_e04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\tfh_e05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\tfh_e06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\tfh_e07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\tfh_e08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\tfh_e09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\tfh_e10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\tfh_e11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\tfh_e12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\tfh_e13b.inf" },

	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\tfh-e04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\tfh-e05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\tfh-e06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\tfh-e07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\tfh-e08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\tfh-e09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\tfh-e10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\tfh-e11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\tfh-e12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\tfh-e13c.inf" },
	
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\tfh-e04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\tfh-e05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\tfh-e06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\tfh-e07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\tfh-e08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\tfh-e09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\tfh-e10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\tfh-e11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\tfh-e12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\tfh-e13d.inf" },*/

	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tfh-e19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tfh-e20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tfh-e21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tfh-e22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tfh-e23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hassassin_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hassassin_03.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nASS.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tfh-E25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Tfh-E25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tfh-E99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TfhE-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\TfhE-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\assxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\assxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\Tfh-E14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\Tfh-E15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\Tfh-E15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\Tfh-E16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\Tfh-E17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\Tfh-E30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\Tfh-E31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\Tfh-E32.inf" },
};

static HeadModelStruct saShamanHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\mmh-e01.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\mmh-e02.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\mmh-e03.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\mmh-e04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\mmh-e05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\mmh-e06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\mmh-e07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\mmh-e08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\mmh-e09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\mmh-e10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\mmh-e11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\mmh-e12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\mmh-e13.inf" },

	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\mmh-e01a.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\mmh-e02a.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\mmh-e03a.inf" },

	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\mmh_e01b.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\mmh_e02b.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\mmh_e03b.inf" },

	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\mmh-e01c.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\mmh-e02c.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\mmh-e03c.inf" },

	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\mmh-e01d.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\mmh-e02d.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\mmh-e03d.inf" },

	/* 
	
	Don't have these tier hair crown models for Shaman

	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\mmh-e04a.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\mmh-e05a.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\mmh-e06a.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\mmh-e07a.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\mmh-e08a.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\mmh-e09a.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\mmh-e10a.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\mmh-e11a.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\mmh-e12a.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\mmh-e13a.inf" },

	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\mmh_e04b.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\mmh_e05b.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\mmh_e06b.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\mmh_e07b.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\mmh_e08b.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\mmh_e09b.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\mmh_e10b.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\mmh_e11b.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\mmh_e12b.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\mmh_e13b.inf" },
	
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\mmh-e04c.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\mmh-e05c.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\mmh-e06c.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\mmh-e07c.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\mmh-e08c.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\mmh-e09c.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\mmh-e10c.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\mmh-e11c.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\mmh-e12c.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\mmh-e13c.inf" },

	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\mmh-e04d.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\mmh-e05d.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\mmh-e06d.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\mmh-e07d.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\mmh-e08d.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\mmh-e09d.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\mmh-e10d.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\mmh-e11d.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\mmh-e12d.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\mmh-e13d.inf" },*/

	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mmh-e19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mmh-e20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mmh-e21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mmh-e22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mmh-e23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hshaman_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hshaman_03.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaSH.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mmh-E25.inf" },
//	{ ITEMID_EasterSheepHat, 0, "char\\tmABCD\\Mmh-E25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mmh-E99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MmhE-18t.inf" },
	{ ITEMID_SoccerHatSpeed, 0, "char\\tmABCD\\MmhE-18t.inf" },
	{ ITEMID_ChristmasGreenHat, 0, "char\\tmABCD\\shxmasg.inf" },
	{ ITEMID_ChristmasRedHat, 0, "char\\tmABCD\\shxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\Mmh-E14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\Mmh-E15t.inf" },
	{ ITEMID_BigHeadValentine, 0, "char\\tmABCD\\Mmh-E15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\Mmh-E16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\Mmh-E17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\Mmh-E30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\Mmh-E31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\Mmh-E32.inf" },
};

