#pragma once


//#define DEV_MODE 			
#define GAME_VERSION		1309
#define GAME_NAME			"Priston Tale - Testing"
#define GAME_XOR			((((GAME_VERSION) * 519 * 16510 * 14 + 595) % 180) + 20)


//TEMP TEMP TEMP - REMOVE IN NEXT UPDATE! <<<<<<<<<<<<<<<<<<
#define TEMP_UPDATE_LEVEL_113_ITEMS
#define TEMP_UPDATE_ITEMIDS

#define CURRENT_SEASONAL_NUM	4				//Increment by 1 at start of next seasonal. i.e. 2 for seasonal number 2, etc. Do not use zero here. When the session ends, leave this number unchanged
//#define SEASONAL_IS_ACTIVE						//Uncomment this when a seasonal server is active. This unlocks all seasonal related features.

#define MAX_DROP_GOLD(lvl)              (33000 + (1000 * lvl))  //33,000 base for Wanted Wolf etc. Then increase limit based on player level. Level 100 = 133,000 per drop (which can occur in higher level map)
#define MAX_GET_ITEM_GOLD_PER_TIME(lvl) static_cast<UINT>(20000 * lvl) //level 100 = 2`000`000 per min, level 10 = 200,000 per min
#define MAX_GET_ITEM_GOLD_PER_TIME(lvl) static_cast<UINT>(20000 * lvl) //level 100 = 2`000`000 per min, level 10 = 200,000 per min
#define MAX_GET_ITEM_GOLD_TIME          60 * 1000

//#define MEASURE_PACKET_EXECUTION_TIME			//For measuring packet execution times
//#define MEASURE_SQL_EXECUTION_TIME			//For measuring SQL execution times
//#define SKILLS_TESTING_TEMP					//To allow access to the seasonal box for testing purposes
//#define RECONNECT_SYSTEM						//For the reconnect system (WIP)
//#define GENERATE_DROP_STATS_IN_DEV_MODE		//To generate drop stats in dev mode. Otherwise when DEV_MODE is not defined, it will be generated (useful for prod)
#define SKILLS_COST_DISCOUNT					//Discount on skill cost. Meant to be temp until all skills are fixed..
#define PACKET_LOG								//Output packet id / name to console window, useful for debugging. Should be disabled for production obviously. Requires DEV_MODE to be set too
#define DEBUG_INVENTORY							//For debugging player's inventory on server side by showing what has been added / removed from inventory
//#define SKILLS_BEHAVIOUR_DEBUG				//To debug skill behavior on client side
//#define SKILL_DEBUG_FLINCH					//Send 'Flinch' text to client side. Useful for flinching debugs
//#define ENCHANTWEAPON_SETTING					//Enable the Enchantment weapon settings in UI on client side. This allows you to choose the specific enchantment. Useful for testing
//#define SKILLS_ALLOW_CANCEL_ANY_SKILLS_TEMP	//Allows you to cancel any skill on client side, however it's buggy
#define ITEMFIXES								//Item system that will add prefix and suffix at random on generated items using pre-defined database values dbo. ( see ../assets/itemfixes.sql )

#define NEWSTATS								//New character/item stats formulas



#define BMPImage				unsigned int
#define TGAImage				unsigned int

#define UNKNOWN					DWORD

#define	PI						3.14159265358979323846f

#define RELEASE(p)			   { if(p != NULL) p->Release(); p = NULL;}
#define INIT(p)				   { if(p != NULL) p->Init();}
#define INITP(p, ptr)		   { if(p != NULL && ptr != NULL) p->Init(ptr);}
#define SAFE_DELETE(ptr)	   { if(ptr) delete ptr; ptr = NULL;}
#define SAFE_DELETE_ARRAY(ptr) { if(ptr) delete[] ptr; ptr = NULL;}
#define SHUTDOWN(p)			   { if(p != NULL) p->Shutdown();}
#define ADDREF(p)			   { if(p != NULL) p->AddRef();}
#define CLEARPTR(p)			   { if(p != NULL) p->Clear();}
#define RESETPTR(p)			   { if(p != NULL) p.reset(); p = NULL;}


#define IMPFNC					static const DWORD
#define STCFNC					static void

#define NAKED					__declspec(naked)
#define NAKEDVOID				__declspec(naked) void

#define PUSHALL					{ __asm PUSH EAX __asm PUSH ECX __asm PUSH EDX __asm PUSH EBX __asm PUSH EBP __asm PUSH ESI __asm PUSH EDI }
#define POPALL					{ __asm POP EDI __asm POP ESI __asm POP EBP __asm POP EBX __asm POP EDX __asm POP ECX __asm POP EAX }

#define NOP						{ __asm NOP }
#define WRITENOP( addr, count )			{ for( int i = 0; i < count; i++ ) (*(BYTE*)(addr+i)) = 0x90; }
#define CRASH					{ __asm { __asm MOV EAX, DWORD PTR DS:[0x00000000] } }
#define JMP( pointer )			{ __asm { __asm MOV EAX, pointer __asm JMP EAX } }
#define JUMP( pointer )			{ __asm JMP DWORD PTR DS:[pointer] }
#define READTHIS( p )			{ __asm { MOV p, ECX } }

#define WRITEDWORD( a, b )		{ *(DWORD*)a = (DWORD)b; }
#define READDWORD( a )			(*(DWORD*)a)

#define WRITEWORD( a, b )		{ *(WORD*)a = (WORD)b; }
#define READWORD( a )			(*(WORD*)a)

#define WRITEBYTE( a, b )		{ *(BYTE*)a = (BYTE)b; }
#define READBYTE( a )			(*(BYTE*)a)

enum EPTAngle : int
{
	PTANGLE_360		= 4096,
	PTANGLE_1		= (PTANGLE_360 / 360),
	PTANGLE_45		= (PTANGLE_360 / 8),
	PTANGLE_90		= (PTANGLE_360 / 4),
	PTANGLE_180		= (PTANGLE_360 / 2),
	PTANGLE_270		= (PTANGLE_180 + PTANGLE_90),
	PTANGLE_Mask	= (PTANGLE_360 - 1),			///ANGCLIP
};

DWORD CALLT( DWORD ptr1, DWORD t );
DWORD CALLT_WITH_ARG1( DWORD ptr1, DWORD t, DWORD arg1 );
DWORD CALLT_WITH_ARG2( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2 );
DWORD CALLT_WITH_ARG3( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3 );
DWORD CALLT_WITH_ARG4( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4 );
DWORD CALLT_WITH_ARG5( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5 );
DWORD CALLT_WITH_ARG6( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6 );
DWORD CALLT_WITH_ARG7( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7 );
DWORD CALLT_WITH_ARG8( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7, DWORD arg8 );
DWORD CALLT_WITH_ARG9( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7, DWORD arg8, DWORD arg9 );
DWORD CALLT_WITH_ARG10( DWORD ptr1, DWORD t, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7, DWORD arg8, DWORD arg9, DWORD arg10 );

DWORD CALL( DWORD ptr1 );
DWORD CALL_WITH_ARG1( DWORD ptr1, DWORD arg1 );
DWORD CALL_WITH_ARG2( DWORD ptr1, DWORD arg1, DWORD arg2 );
DWORD CALL_WITH_ARG3( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3 );
DWORD CALL_WITH_ARG4( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4 );
DWORD CALL_WITH_ARG5( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5 );
DWORD CALL_WITH_ARG6( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6 );
DWORD CALL_WITH_ARG7( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7 );
DWORD CALL_WITH_ARG8( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7, DWORD arg8 );
DWORD CALL_WITH_ARG9( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7, DWORD arg8, DWORD arg9 );
DWORD CALL_WITH_ARG10( DWORD ptr1, DWORD arg1, DWORD arg2, DWORD arg3, DWORD arg4, DWORD arg5, DWORD arg6, DWORD arg7, DWORD arg8, DWORD arg9, DWORD arg10 );



#define	smPLAYBUFF_ITEM_BODY			0
#define	smPLAYBUFF_ITEM_LEFT			1
#define	smPLAYBUFF_ITEM_RIGHT			2
#define	smPLAYBUFF_ITEM_SKIL			3

#define smPLAYBUFF_FRAME_NONE 			0xFFFF0000
#define CHAR_FRAME_MASK					0x00FFFFFF
#define CHAR_FRAME_SELSHIFT				24
#define PLAYBUFF_MASK					255

#define NPCID_MUSHROOM_CAVE_KEEPER 1
#define NPCID_MISCELLANEOUS_STORE_LYNN 2
#define NPCID_MISCELLANEOUS_STORE_LETTE 3
#define NPCID_CURSED_TEMPLE_GUARDIAN 4
#define NPCID_BLACKSMITH_FRAIN 5
#define NPCID_BLACKSMITH_ANDREW 6
#define NPCID_EVENT_GIRL 7
#define NPCID_FORCE_MASTER_1 8
#define NPCID_GARDENER_OMI 9
#define NPCID_ATLANTIS_GUARD_1 10
#define NPCID_ATLANTIS_GUARD_2 11
#define NPCID_HAIR_STYLELIST 12
#define NPCID_HUNTRESS_3 13
#define NPCID_ITEM_COLLECTOR_LINH 14
#define NPCID_ITEM_DISTRIBUTOR 15
#define NPCID_MAYOR_MAZ 16
#define NPCID_BATTLE_PORTAL_1 17
#define NPCID_PRECIOUS_ITEM_SHOP 18
#define NPCID_ATLANTIS_PRISON_GUARD 19
#define NPCID_ATLANTIS_SPECIAL_ITEM_SHOP 20
#define NPCID_STONESMITH_HONG 21
#define NPCID_SUPPLY_STORE_NY 22
#define NPCID_WAREHOUSE_KEEPER_DOJ 23
#define NPCID_CLEVER_DAEMON 24
#define NPCID_BATTLE_CONTROLS 25
#define NPCID_FORCE_MASTER_2 26
#define NPCID_BATTLE_GUARD 27
#define NPCID_BATTLE_MASTER 28
#define NPCID_BATTLE_PORTAL_2 29
#define NPCID_MYSTERY_PORTAL_1 30
#define NPCID_BATTLE_POTION_STORE 31
#define NPCID_SECRETARY_DUNNAVAN 32
#define NPCID_SANCTUARY_KEEPER 33
#define NPCID_ESU_THE_MANAGER 34
#define NPCID_BLESS_CASTLE_GUARD 35
#define NPCID_ROSSA 36
#define NPCID_SHELLBI 37
#define NPCID_ROZALIE 38
#define NPCID_KARA 39
#define NPCID_KIRI 40
#define NPCID_DUNGEON_KEEPER_1 41
#define NPCID_CURSED_LAND_BRIDGE_GUARD 42
#define NPCID_MISCELLANEOUS_STORE_SAVY 43
#define NPCID_EURA_FORCE_MASTER 44
#define NPCID_EURA_GUARD_ANDREI 45
#define NPCID_MISCELLANEOUS_STORE_EURA 46
#define NPCID_WAREHOUSE_KEEPER_EURA 47
#define NPCID_SUPPLY_STORE_RESIA 48
#define NPCID_EURA_IRON_GUARD 49
#define NPCID_IRON_GUARD 50
#define NPCID_MISCELLANEOUS_STORE_ROBIN 51
#define NPCID_CAVE_GUARD 52
#define NPCID_PITCHMAN_DELA 53
#define NPCID_LOST_CASTLE_BRIDGE_GUARD 54
#define NPCID_MISCELLANEOUS_STORE_EVY 55
#define NPCID_CURSED_MILTER 56
#define NPCID_MISCELLANEOUS_STORE_IVONNE 57
#define NPCID_DESERT_GUARD_1 58
#define NPCID_FOREST_GUARD 59
#define NPCID_MYSTERY_PORTAL_2 60
#define NPCID_CIVILIAN_MINUREN 61
#define NPCID_DESERT_GUARD_2 62
#define NPCID_BLACKSMITH_UMPH 63
#define NPCID_BLACKSMITH_DROL 64
#define NPCID_NAVISKO_GUARD 65
#define NPCID_MAGIC_STORE_3RD_BRANCH 66
#define NPCID_MISCELLANEOUS_STORE_BYANT 67
#define NPCID_WAREHOUSE_KEEPER_OMIDOR 68
#define NPCID_ARCANE_MORIPH 69
#define NPCID_MASTER_ARAD 70
#define NPCID_MOLLY_THE_GRANNY 71
#define NPCID_PHILLAI_CLAN_MASTER 72
#define NPCID_BLACKSMITH_BARTZ 73
#define NPCID_BLACKSMITH_DEFRAIN 74
#define NPCID_PHILLAI_FORCE_MASTER 75
#define NPCID_PHILLAI_GUARD_1 76
#define NPCID_PHILLAI_GUARD_2 77
#define NPCID_HUNTRESS 78
#define NPCID_WITCHCRAFT_STORE_1 79
#define NPCID_CLEVER_NEWTER 80
#define NPCID_PHILLAI_PARTY_SHOP 81
#define NPCID_PHILLAI_PRISON_GUARD 82
#define NPCID_PHILLAI_QUEST_SHOP 83
#define NPCID_ROYAL_MAGE_RAY 84
#define NPCID_PHILLAI_ROBE_SHOP 85
#define NPCID_PHILLAI_SHELTOM_SHOP 86
#define NPCID_WITCHCRAFT_ACADEMY_RAYMON 87
#define NPCID_PHILLAI_SPECIAL_ITEM_SHOP 88
#define NPCID_MISCELLANEOUS_STORE_PHILLYA 89
#define NPCID_WAREHOUSE_KEEPER_LAVENDAR 90
#define NPCID_RICARTEN_ARMOR_SHOP 91
#define NPCID_GOOD_BOY_LONGBO 92
#define NPCID_RICARTEN_CLAN_MASTER 93
#define NPCID_KNIGHT_COMMANDER_DERIK 94
#define NPCID_BLACKSMITH_GODEN 95
#define NPCID_BLACKSMITH_GUS 96
#define NPCID_RICARTEN_FORCE_MASTER 97
#define NPCID_RICARTEN_GUARD_1 98
#define NPCID_RICARTEN_GUARD_2 99
#define NPCID_HUNTRESS_1 100
#define NPCID_MIXING_CRAFTSMAN_MORALD 101
#define NPCID_NINE_FOX 102
#define NPCID_RICARTEN_PARTY_SHOP 103
#define NPCID_RICARTEN_PRISON_GUARD 104
#define NPCID_RICARTEN_QUEST_SHOP_WANDA 105
#define NPCID_SANTA_GIRL 106
#define NPCID_MASTER_SHALON 107
#define NPCID_SHELTOM_SHOP_MORIPHS_SON 108
#define NPCID_SKILL_MASTER_VERKAN 109
#define NPCID_SOCCERFAN 110
#define NPCID_RICARTEN_SPECIAL_ITEM_SHOP 111
#define NPCID_MISCELLANEOUS_STORE_NAMY 112
#define NPCID_TRAVELLER 113
#define NPCID_WAREHOUSE_KEEPER_ARENT 114
#define NPCID_INVENTOR_OF_WARPGATE 115
#define NPCID_WISEMAN_VAL 116
#define NPCID_BRONZE_WOLVERINE 117
#define NPCID_GOLDEN_WOLVERINE 118
#define NPCID_SILVER_WOLVERINE 119
#define NPCID_LOST_WANDERER 120
#define NPCID_BLACKSMITH_RUGA 121
#define NPCID_LAKE_GUARD 122
#define NPCID_MAGIC_STORE_2ND_BRANCH 123
#define NPCID_RUINEN_KIOSK 124
#define NPCID_SECRETARY_KARINA 125
#define NPCID_ARIEL 126
#define NPCID_CASA_1 127
#define NPCID_NOAS 128
#define NPCID_SYLPI 129
#define NPCID_ALBUS_P_W_B_DUMBLEDORE 130
#define NPCID_JOHN_THE_ADVENTURER 132
#define NPCID_DAILY_MISSIONS_ADVISOR_IAN 133
#define NPCID_ATLANTIS_AMBASSADOR_RENNAN 134
#define NPCID_LUCY 135
#define NPCID_GM_SHOP 136
#define NPCID_ITEM_SHOP 137
#define NPCID_BLACKSMITH_SOLO 138
#define NPCID_MISCELLANEOUS_STORE_REY 139
#define NPCID_MISCELLANEOUS_STORE_LEIA 140
#define NPCID_BLACKSMITH_PLAGUEIS 141
#define NPCID_HUNTRESS_2 142
#define NPCID_THE_MESSENGER_SAPHIR 143
#define NPCID_DUNGEON_KEEPER_2 144
#define NPCID_CURSED_TEMPLE_GUARD 145
#define NPCID_LARRY_THE_RETIRED_MINER 146
#define NPCID_MISCELLANEOUS_STORE_CINDY 147
#define NPCID_MASTER_VALDO 148
#define NPCID_INSTRUCTOR_ANNIE 150
#define NPCID_MISCELLANEOUS_STORE_VALERIYA 151
#define NPCID_IHIN 152
#define NPCID_MARINA 153
#define NPCID_COWARD_HERMIT 154
#define NPCID_WAREHOUSE_KEEPER 155
#define NPCID_LEE_THE_RUNE_MASTER 156
#define NPCID_DOS_THE_DRILL_MASTER 160
#define NPCID_RUDOLPH_THE_REINDEER 161
#define NPCID_MISCELLANEOUS_STORE_NAALIS 162
#define NPCID_MISCELLANEOUS_STORE_NIMPHY 163
#define NPCID_BOSS_HUNTER_WILLIAM 164
#define NPCID_WAREHOUSE_KEEPER_BUJA 166
#define NPCID_INSTRUCTOR_MILLIE 168
#define NPCID_CASA_2 169
#define NPCID_KALIRA 172
#define NPCID_MILA 173
#define NPCID_KIRA 174
#define NPCID_QUEST_BOARD 177
#define NPCID_RUINEN_QUEST_MASTER 178
#define NPCID_CURSED_LAND_QUEST_MASTER 179
#define NPCID_NAVISKO_QUEST_MASTER 180
#define NPCID_DUNGEON_1_QUEST_MASTER 181
#define NPCID_BEEHIVE_CAVE_QUEST_MASTER 182
#define NPCID_DARK_SANCTUARY_QUEST_MASTER 183
#define NPCID_CURSED_TEMPLE_1_QUEST_MASTER 184
#define NPCID_RAILROAD_OF_CHAOS_QUEST_MASTER 185
#define NPCID_HEART_OF_PERUM_QUEST_MASTER 186
#define NPCID_THE_LONE_WOLF 187
#define NPCID_CURSED_TEMPLE_2_QUEST_MASTER 188
#define NPCID_OASIS_QUEST_MASTER 189
#define NPCID_DUNGEON_2_QUEST_MASTER 190
#define NPCID_DUNGEON_3_QUEST_MASTER 191
#define NPCID_GALLUBIA_VALLEY_QUEST_MASTER 192
#define NPCID_MISCELLANEOUS_STORE_KAIRI 193
#define NPCID_MISCELLANEOUS_STORE_MIDNA 194
#define NPCID_MISCELLANEOUS_STORE_SHEPARD 195
#define NPCID_MISCELLANEOUS_STORE_ALYX 196
#define NPCID_MISCELLANEOUS_STORE_TIFA 197
#define NPCID_MISCELLANEOUS_STORE_YUNA 198
#define NPCID_MISCELLANEOUS_STORE_GORDEN 199
#define NPCID_MARK_LEADERBOARD_TRACKER 200
#define NPCID_LAND_OF_CHAOS_QUEST_MASTER 201
#define NPCID_ELITE_LABORATORY_GUARD 202
#define NPCID_LOST_TEMPLE_QUEST_MASTER 203
#define NPCID_MARCUS_SOL 205
#define NPCID_S2_WAREHOUSE_KEEPER_AYA 207
#define NPCID_S2_WAREHOUSE_KEEPER_CEDAR 208
#define NPCID_BLACKSMITH_JAMES 209
#define NPCID_BLACKSMITH_JOHN 210
#define NPCID_WITCHCRAFT_STORE_2 211
#define NPCID_MISCELLANEOUS_STORE_NATASHA 213
#define NPCID_ROSA 215
#define NPCID_BATTLEFIELD_QUEST_MASTER 223
#define NPCID_SAILOR_SPARROW 238

#define	snCHAR_SOUND_FIGHTER		0x0001
#define	snCHAR_SOUND_MECHANICAN		0x0002
#define	snCHAR_SOUND_PIKEMAN		0x0004
#define	snCHAR_SOUND_ARCHER			0x0003

#define	snCHAR_SOUND_KNIGHT			0x0006
#define	snCHAR_SOUND_ATALANTA		0x0005
#define	snCHAR_SOUND_PRIESTESS		0x0008
#define	snCHAR_SOUND_MAGICIAN		0x0007

#define	snCHAR_SOUND_CYCLOPS		0x1000
#define	snCHAR_SOUND_HOBGOBLIN		0x1010
#define	snCHAR_SOUND_IMP			0x1020
#define	snCHAR_SOUND_MINIG			0x1030
#define	snCHAR_SOUND_PLANT			0x1040
#define	snCHAR_SOUND_SKELETON		0x1050
#define	snCHAR_SOUND_ZOMBI			0x1060
#define	snCHAR_SOUND_OBIT			0x1070

#define	snCHAR_SOUND_HOPT			0x1080
#define	snCHAR_SOUND_BARGON			0x1090
#define	snCHAR_SOUND_LEECH			0x10A0
#define	snCHAR_SOUND_MUSHROOM		0x10B0

#define snCHAR_SOUND_ARMA			0x10C0
#define snCHAR_SOUND_SCORPION		0x10D0

#define	snCHAR_SOUND_HEADCUTTER		0x1100
#define	snCHAR_SOUND_SANDLEM		0x1110
#define	snCHAR_SOUND_WEB			0x1120
#define	snCHAR_SOUND_HOPYKING		0x1130
#define	snCHAR_SOUND_CRIP			0x1140
#define	snCHAR_SOUND_BUMA			0x1150
#define	snCHAR_SOUND_DECOY			0x1160
#define	snCHAR_SOUND_DORAL			0x1170
#define	snCHAR_SOUND_FIGON			0x1180
#define	snCHAR_SOUND_STONEGIANT		0x1190
#define	snCHAR_SOUND_GREVEN			0x11A0
#define	snCHAR_SOUND_ILLUSIONKNIGHT	0x11B0
#define	snCHAR_SOUND_SKELETONRANGE	0x11C0
#define	snCHAR_SOUND_SKELETONMELEE	0x11D0
#define	snCHAR_SOUND_WOLVERLIN		0x11E0

#define	snCHAR_SOUND_RABIE			0x1200
#define	snCHAR_SOUND_MUDY			0x1210
#define	snCHAR_SOUND_SEN			0x1220
#define	snCHAR_SOUND_EGAN			0x1230
#define	snCHAR_SOUND_BEEDOG			0x1240
#define	snCHAR_SOUND_MUTANTPLANT	0x1250
#define	snCHAR_SOUND_MUTANTRABIE	0x1260
#define	snCHAR_SOUND_MUTANTTREE		0x1270
#define	snCHAR_SOUND_AVELISK		0x1280
#define	snCHAR_SOUND_NAZ			0x1290
#define	snCHAR_SOUND_MUMMY			0x12A0
#define	snCHAR_SOUND_HULK			0x12B0
#define	snCHAR_SOUND_SUCCUBUS		0x12C0
#define	snCHAR_SOUND_DAWLIN			0x12D0
#define	snCHAR_SOUND_SHADOW			0x12E0
#define	snCHAR_SOUND_BERSERKER		0x12F0
#define	snCHAR_SOUND_IRONGUARD		0x1300
#define	snCHAR_SOUND_FURY			0x1310
#define	snCHAR_SOUND_SLIVER			0x1320
#define	snCHAR_SOUND_HUNGKY			0x1330

#define	snCHAR_SOUND_RATOO			0x1340
#define	snCHAR_SOUND_STYGIANLORD	0x1350
#define	snCHAR_SOUND_OMICRON		0x1360
#define	snCHAR_SOUND_DMACHINE		0x1370
#define	snCHAR_SOUND_METRON			0x1380

#define	snCHAR_SOUND_MRGHOST		0x1390

#define	snCHAR_SOUND_VAMPIRICBAT	0x13A0
#define	snCHAR_SOUND_MIREKEEPER		0x13B0
#define	snCHAR_SOUND_MUFFIN			0x13C0
#define	snCHAR_SOUND_SOLIDSNAIL		0x13D0
#define	snCHAR_SOUND_BEEVIL			0x13E0
#define	snCHAR_SOUND_DIREBEE		0x13F0
#define	snCHAR_SOUND_NIGHTMARE		0x1400
#define	snCHAR_SOUND_STONEGOLEM		0x1410
#define	snCHAR_SOUND_THORNCRAWLER	0x1420
#define	snCHAR_SOUND_HEAVYGOBLIN	0x1430
#define	snCHAR_SOUND_EVILPLANT		0x1440
#define	snCHAR_SOUND_HAUNTINGPLANT	0x1450
#define	snCHAR_SOUND_DARKKNIGHT		0x1460
#define	snCHAR_SOUND_GUARDIAN_SAINT	0x1470


#define	snCHAR_SOUND_CHAINGOLEM		0x1500
#define	snCHAR_SOUND_DEADZONE		0x1510
#define	snCHAR_SOUND_GROTESQUE		0x1520
#define	snCHAR_SOUND_HYPERMACHINE	0x1530
#define	snCHAR_SOUND_IRONFIST		0x1540
#define	snCHAR_SOUND_MORGON			0x1550
#define	snCHAR_SOUND_MOUNTAIN		0x1560
#define	snCHAR_SOUND_RAMPAGE		0x1570
#define	snCHAR_SOUND_RUNICGUARDIAN	0x1580
#define	snCHAR_SOUND_SADNESS		0x1590
#define	snCHAR_SOUND_TOWERGOLEM		0x15A0
#define	snCHAR_SOUND_VAMPRICBEE		0x15B0
#define	snCHAR_SOUND_VAMPRICMACHINE	0x15C0
#define	snCHAR_SOUND_OMU			0x15D0

#define	snCHAR_SOUND_AVELIN_ARCHER	0x15E0
#define	snCHAR_SOUND_AVELIN_QUEEN	0x15F0

#define	snCHAR_SOUND_BABEL			0x1600

#define	snCHAR_SOUND_MYSTIC			0x1610
#define	snCHAR_SOUND_ICEGOBLIN		0x1620
#define	snCHAR_SOUND_COLDEYE		0x1630
#define	snCHAR_SOUND_FROZEN			0x1640
#define	snCHAR_SOUND_ICEGOLEM		0x1650
#define	snCHAR_SOUND_FROST			0x1660
#define	snCHAR_SOUND_CHAOSCARA		0x1670
#define	snCHAR_SOUND_DEATHKNIGHT	0x1680

//Greedy Lake Extra Monster
#define	snCHAR_SOUND_GREATE_GREVEN	0x1700
#define	snCHAR_SOUND_LIZARDFOLK		0x1710
#define	snCHAR_SOUND_M_LORD			0x1720
#define	snCHAR_SOUND_SPIDER			0x1730
#define	snCHAR_SOUND_STINGRAY		0x1740
#define	snCHAR_SOUND_STRIDER		0x1750


//Ice 2 Additional Monster
#define	snCHAR_SOUND_TURTLE_CANNON	0x1800
#define	snCHAR_SOUND_DEVIL_BIRD		0x1810
#define	snCHAR_SOUND_BLIZZARD_GIANT	0x1820
#define	snCHAR_SOUND_KELVEZU		0x1830

//New field added
#define	snCHAR_SOUND_DARKPHALANX	0x1840
#define	snCHAR_SOUND_BLOODYKNIGHT	0x1850
#define	snCHAR_SOUND_CHIMERA		0x1860
#define	snCHAR_SOUND_FIREWORM		0x1870
#define	snCHAR_SOUND_HELLHOUND		0x1880
#define	snCHAR_SOUND_DARKGUARD		0x1890
#define	snCHAR_SOUND_DARKMAGE		0x18A0

#define	snCHAR_SOUND_MOKOVA			0x18B0
#define	snCHAR_SOUND_TEMPLEGUARD	0x18C0
#define	snCHAR_SOUND_SETO			0x18D0
#define	snCHAR_SOUND_KINGSPIDER		0x18E0

//pluto new field monster
#define snCHAR_SOUND_REVIVED_KNIGHT		0x18F0	//Knight
#define snCHAR_SOUND_REVIVED_MAGICIAN	0x1900 //Magician
#define snCHAR_SOUND_REVIVED_ARCHER		0x1910 //Archer
#define snCHAR_SOUND_REVIVED_ATALANTA	0x1920 //Atalanta
#define snCHAR_SOUND_REVIVED_FIGTHER	0x1930 //Fighter
#define snCHAR_SOUND_REVIVED_MECANICIAN	0x1940 //Mechanism
#define snCHAR_SOUND_REVIVED_PIKEMAN	0x1950 //Pikeman
#define snCHAR_SOUND_REVIVED_PRIESTESS	0x1960 //Pristis
#define snCHAR_SOUND_DEADHOPT			0x1970 //Dead Hopi
#define snCHAR_SOUND_DEADKINGHOPY		0x1980 //Undead Kinghope
#define snCHAR_SOUND_GORGON				0x1990 //Gorgon
#define snCHAR_SOUND_HOBOGOLEM			0x19A0 //Hobogorem

//Park Jae-won-Cursed Temple 3rd Floor (New Field Monster)
#define snCHAR_SOUND_NIKEN				0x19B0 //Nicken
#define snCHAR_SOUND_MIMIC				0x19C0 //Mimic
#define snCHAR_SOUND_KINGBAT			0x19D0 //Kingbat
#define snCHAR_SOUND_GOBLINSHAMAN		0x19E0 //Goblin Shaman
#define snCHAR_SOUND_HEST				0x19F0 //Hest

//Park Jae-won-Endless Tower 3rd Floor (New Field Monster)
#define snCHAR_SOUND_RUCA				0x2100 //Luca
#define snCHAR_SOUND_NAZSENIOR			0x2110 //Naz Senior
#define snCHAR_SOUND_IGOLATION			0x2120 //Igolation
#define snCHAR_SOUND_KAKOA				0x2130 //cacoa
#define snCHAR_SOUND_SPRIN				0x2140 //Sprin
#define snCHAR_SOUND_UNDEADMAPLE		0x2150 //Undead Maple
#define snCHAR_SOUND_XETAN				0x2160 //ammunition

//Park Jae-won-Fortune Event Monster Added
#define snCHAR_SOUND_BEBECHICK			0x2170 //Baby Cuckoo
#define snCHAR_SOUND_PAPACHICK			0x2180 //Dad Cuckold

//World Cup Monster
#define	snCHAR_SOUND_WORLDCUP		0x1A00

#define	snCHAR_SOUND_NPC_MORIF		0x2010
#define	snCHAR_SOUND_NPC_MOLLYWOLF	0x2012
#define	snCHAR_SOUND_NPC_SKILLMASTER	0x2020
#define	snCHAR_SOUND_NPC_MAGICMASTER	0x2030


#define	snCHAR_SOUND_S_WOLVERLIN	0x3010
#define	snCHAR_SOUND_S_METALGOLEM	0x3020
#define	snCHAR_SOUND_S_F_ELEMENTAL	0x3030


#define	snCHAR_SOUND_CASTLE_DOOR		0x5010
#define	snCHAR_SOUND_CASTLE_CRYSTAL_R	0x5020
#define	snCHAR_SOUND_CASTLE_CRYSTAL_G	0x5021
#define	snCHAR_SOUND_CASTLE_CRYSTAL_B	0x5022
#define	snCHAR_SOUND_CASTLE_CRYSTAL_N	0x5023
#define	snCHAR_SOUND_CASTLE_TOWER_B		0x5030

//Mercenaries
#define	snCHAR_SOUND_CASTLE_SOLDER_A	0x5100
#define	snCHAR_SOUND_CASTLE_SOLDER_B	0x5110
#define	snCHAR_SOUND_CASTLE_SOLDER_C	0x5120

//Chapter Bye-Watermelon Monster
#define	snCHAR_SOUND_WATERMELON			0x5130

//Chapter Bye-Soul Stone
#define	snCHAR_SOUND_S_AVELIN						0x5140
#define	snCHAR_SOUND_S_BAGON						0x5150
#define	snCHAR_SOUND_S_BEEDOG					0x5160
#define	snCHAR_SOUND_S_BEEVIL						0x5170
#define	snCHAR_SOUND_S_BERSERKER				0x5180
#define	snCHAR_SOUND_S_BUMA						0x5190
#define	snCHAR_SOUND_S_COKRIS						0x51A0
#define	snCHAR_SOUND_S_COLDEYE					0x51B0
#define	snCHAR_SOUND_S_CRYPT						0x51C0
#define	snCHAR_SOUND_S_CYCLOPS					0x51D0
#define	snCHAR_SOUND_S_DEADZONE				0x51E0
#define	snCHAR_SOUND_S_DECOY						0x51F0
#define	snCHAR_SOUND_S_DMACHINE				0x5200
#define	snCHAR_SOUND_S_EVILSNAIL					0x5210
#define	snCHAR_SOUND_S_GREVEN					0x5220
#define	snCHAR_SOUND_S_GROTESQUE				0x5230
#define	snCHAR_SOUND_S_ICEGOBLIN				0x5240
#define	snCHAR_SOUND_S_ICEGOLEM				0x5250
#define	snCHAR_SOUND_S_INCUBUS					0x5260
#define	snCHAR_SOUND_S_KINGHOPY					0x5270
#define	snCHAR_SOUND_S_LEECH						0x5280
#define	snCHAR_SOUND_S_LIZARDFOLK				0x5290
#define	snCHAR_SOUND_S_MEPHIT						0x52A0
#define	snCHAR_SOUND_S_METRON					0x52B0
#define	snCHAR_SOUND_S_MUFFIN						0x52C0
#define	snCHAR_SOUND_S_MUMMY					0x52D0
#define	snCHAR_SOUND_S_NAZ							0x52E0
#define	snCHAR_SOUND_S_OMEGA						0x52F0
#define	snCHAR_SOUND_S_RAMPAGE					0x5300
#define	snCHAR_SOUND_S_SADNESS					0x5310
#define	snCHAR_SOUND_S_SLAUGHTER				0x5320
#define	snCHAR_SOUND_S_SLAYON					0x5330
#define	snCHAR_SOUND_S_SLIVER						0x5340
#define	snCHAR_SOUND_S_TITAN						0x5350
#define	snCHAR_SOUND_S_TOWERGOLEM			0x5360
#define	snCHAR_SOUND_S_TYPHOON					0x5370
#define	snCHAR_SOUND_S_VAMPIRICBAT			0x5380
#define	snCHAR_SOUND_S_WITCH						0x5390
#define	snCHAR_SOUND_S_ZOMBIE					0x53A0


#define	esSOUND_FIGON_IMPACT		10

#define AGING_SUB_LEVEL 10

#define SKILL_PLAY_BLESS_ABSORB			0xA0
#define SKILL_PLAY_BLESS_DAMAGE			0xA1
#define SKILL_PLAY_BLESS_EVADE			0xA2
#define SKILL_PLAY_BLESS_SIEGE_ITEM		0xA8

#define SKILL_PLAY_FIRE_CRYSTAL			0xB0
#define SKILL_PLAY_LIGHTNING_CRYSTAL	0xB1
#define SKILL_PLAY_ICE_CRYSTAL			0xB2
#define SKILL_PLAY_CHAOSCARA_VAMP		0xB8

#define SKILL_PLAY_PET_ATTACK		0xC0
#define SKILL_PLAY_PET_ATTACK2		0xC1

#define SKILL_PLAY_SOD_ITEM			0xD0
//#define SKILL_PLAY_METEO			0xE0
#define SKILL_PLAY_SPEACIAL			0xF0
#define	SKILL_PLAY_LOVELY_LIFE		0xF1

#define	SKILL_EFFECT_FIREFLOWER		0x12000010

#define MAX_EFFECTOBJECT_BUFFER		500
#define MAX_TIMEOBJECT_BUFFER		100

#define MAX_MATERIAL_NUM			100
#define MAX_OBJECT_NUM				100


#define EFFECT_NORMAL_HIT1		100
#define EFFECT_NORMAL_HIT2		150

#define EFFECT_CRITICAL_HIT1    200
#define EFFECT_CRITICAL_HIT2    210

#define EFFECT_LEVELUP1		    300

#define EFFECT_ROUND_IMPACT     400
#define EFFECT_GAME_START1		500

#define EFFECT_POTION1			600
#define EFFECT_POTION2			700
#define EFFECT_POTION3			800
#define EFFECT_BROKEN1			850

#define EFFECT_DAMAGE1			900
#define EFFECT_GAS1				1000
#define EFFECT_DUST1			1100
#define EFFECT_LIGHT1			1200
#define EFFECT_BANDI1			1300
#define EFFECT_GATE1			1350

#define EFFECT_TEST1			1400
#define EFFECT_TEST2			2000
#define EFFECT_PARTICLE_BOW1	1500
#define EFFECT_PARTICLE_BOW2	2520
#define EFFECT_FIRE_HIT1		3000
#define EFFECT_FIRE_HIT2		3200
#define EFFECT_RETURN1			3500
#define EFFECT_MECHANICBOMB_DUST1 4000
#define EFFECT_SHIELD1_PARTICLE   5000
#define EFFECT_AGING			  5001


#define SKILL_NONE							500
#define SKILL_HOMING						5500
#define SKILL_METEO							6000
#define SKILL_UP1							6500


#define SKILL_TORNADO2     		6800
#define SKILL_GREAT_SMASH2     	6810



#define SKILL_TORNADO3     		6801
#define SKILL_GREAT_SMASH3     	6811




#define EFFECT_PHYSICAL_ABSORB_DAMAGE		7000
#define EFFECT_LAND_MINNING_BOMB			8000
#define SKILL_SHIELD1						20000
#define SKILL_SHIELD2						20001
#define EFFECT_SHIELD2_PARTICLE				20002

#define EFFECT_SPARK1						24000
#define EFFECT_SPARK2						24001


#define MONSTER_PIGON_POWER1				29000
#define MONSTER_PIGON_PARTICLE1				29001
#define MONSTER_PIGON_SHOT1					29002

#define MONSTER_PIGON_POWER2				29003
#define MONSTER_PIGON_PARTICLE2				29004


#define MONSTER_PIGON_PARTICLE1_BLH				29005


#define MONSTER_HP_OVERRIDE					30000

#define MONSTER_WEB_SHOT1					35000
#define MONSTER_WEB_HIT1					30000

#define MONSTER_IMP_SHOT1					35100
#define MONSTER_IMP_HIT1					35200

#define MONSTER_IMP_SHOT2					35101
#define MONSTER_IMP_HIT2					35201

#define MONSTER_IMP_SHOT3					35102
#define MONSTER_IMP_HIT3					35102


#define MONSTER_MEPHIT_SHOT1				35300
#define MONSTER_MEPHIT_HIT1					35400
#define MONSTER_HEADER_CUTTER_HIT1			35411
#define MONSTER_HULK_HIT1					35422
#define MONSTER_FURY_MAGIC1					35623

#define MONSTER_OMICRON_HIT1				35626
#define MONSTER_DMACHINE_PARTICLE1			35628
#define MONSTER_DMACHINE_MISSILE1			35630
#define MONSTER_DMACHINE_MISSILE2			35631

#define MONSTER_STYGIANLORD_SHOT1			35633
#define MONSTER_STYGIANLORD_PARTICLE1		35634
#define MONSTER_STYGIANLORD_MAGIC1			35635

#define MONSTER_SERQBUS_SHOT1				70000
#define MONSTER_SERQBUS_SHOT2               70001
#define MONSTER_SERQBUS_SHOT3               70002

#define MONSTER_SERQBUS_MAGIC1              70003
#define MONSTER_SERQBUS_MAGIC2              70004
#define MONSTER_SERQBUS_MAGIC3              70005

#define MONSTER_SERQBUS_MAGIC_ATTACK1       70006
#define MONSTER_SERQBUS_MAGIC_ATTACK2       70007
#define MONSTER_SERQBUS_MAGIC_ATTACK3       70008


#define MONSTER_SERQBUS_STATE1				70009
#define MONSTER_SERQBUS_STATE2				70010
#define MONSTER_SERQBUS_STATE3              70011


#define MONSTER_SHADOW_SHOT1                35639


#define MONSTER_MEPHIT_SHOT2				35301
#define MONSTER_MEPHIT_HIT2					35401



#define MONSTER_FORZENMIST_SHOT1				60601
#define MONSTER_FORZENMIST_HIT1					60611

#define MONSTER_FORZENMIST_SHOT2				60602
#define MONSTER_FORZENMIST_HIT2					60612

#define EFFECT_ICE_HIT1					60650
#define EFFECT_ICE_HIT2					60651
#define MONSTER_COLDEYE_SKILL			60680

#define MONSTER_VALENTO_HIT1			60690
#define MONSTER_VALENTO_HIT2			60691

#define MONSTER_POSION_STATE1				60700

#define MONSTER_MUMMY_SHOT				60710

#define MONSTER_TURTLECANON_SHOT				60720

#define EFFECT_FIRE_CRACKER				60730
#define EFFECT_FIRE_CRACKER_HIT				60731


#define EFFECT_CHIMERA_SKILL				60740
#define EFFECT_BLOODKNIGHT_SKILL				60741




#define ARROW_OF_RAGE_POWER1				35401
#define SKILL_ARROW_OF_RAGE_END				40000

#define SKILL_RAGE_OF_ZECRAM_POWER1			44000
#define SKILL_RAGE_OF_ZECRAM_HIT1			44001
#define SKILL_RAGE_OF_ZECRAM_HIT2			44002
#define SKILL_MORTAL_BLOW_HIT				44003

#define SKILL_AVALANCHE_PARTICLE			50001
#define EFFECT_ARROW_OF_RAGE_HIT1			53000

#define EFFECT_GROUND_PIKE_PARTICLE			54000
#define EFFECT_STUN1						55000
#define EFFECT_FALCON_GATE1					56000


#define EFFECT_TERRAIN_WAVE					60000


#define SKILL_METALARMOR					61000



#define SIN_OPEN		1
#define SIN_CLOSE		0


#define MAX_SIN_KIND_INTER		13

#define SIN_CHARSTATUS	0
#define SIN_INVENTORY	1
#define SIN_SHOP		2
#define SIN_SKILL		3
#define SIN_TRADE		4
#define SIN_WAREHOUSE	5
#define SIN_CRAFTITEM	6
#define SIN_AGING		7
#define SIN_MYSHOP		8
#define SIN_CHARSHOP	9
#define SIN_SMELTING	10
#define SIN_MANUFACTURE 11
#define	SIN_MIXTURE_RESET	12
#define SIN_SYSTEM		13


#define SIN_ALL_CLOSE	100



#define SIN_AGING_ATTACK			100
#define SIN_AGING_CRITICAL			101
#define SIN_AGING_BLOCK				102
#define SIN_AGING_DEFENSE_ORB		103
#define SIN_AGING_DEFENSE_ARMOR		104
#define SIN_AGING_DEFENSE_BOOTS		105
#define SIN_AGING_DEFENSE_GLOVES	106
#define SIN_AGING_DEFENSE_ARMLETS	107


#define	sinITEM_WEAPON	0x01000000
#define	sinITEM_DEFENCE	0x02000000
#define	sinITEM_MASK1	0xFF000000
#define	sinITEM_MASK2	0xFFFF0000
#define	sinITEM_MASK3	0x0000FFFF


#define		RESTART_FEILD		1
#define		RESTART_TOWN		2
#define		RESTART_EXIT		3


#define     HA_DEFANCE			1
#define     HA_BLOCK			2
#define     HA_EVASION			3


#define STINGRAY_POSION_TIME	5


#define	SKILL_APPMASK_EXTREME_SHIELD		0x0001
#define	SKILL_APPMASK_PHYSICAL_ABSORB		0x0002
#define	SKILL_APPMASK_AUTOMATION			0x0004
#define	SKILL_APPMASK_ANGER					0x0008
#define	SKILL_APPMASK_SPARK_SHIELD			0x0010
#define	SKILL_APPMASK_GODLY_SHIELD			0x0020


#define	SKILL_APPMASK_HOLY_BODY				0x00010000


//////////// Mechanism skill //////////////
#define SKILL_PLAY_EXTREME_SHIELD	0x01
#define SKILL_PLAY_MECHANIC_BOMB	0x02
#define	SKILL_PLAY_PHYSICAL_ABSORB	0x03
#define	SKILL_PLAY_POISON_ATTRIBUTE	0x04

#define	SKILL_PLAY_GREAT_SMASH		0x05
#define	SKILL_PLAY_MAXIMIZE			0x06
#define	SKILL_PLAY_AUTOMATION		0x07
#define	SKILL_PLAY_SPARK			0x08

#define	SKILL_PLAY_METAL_ARMOR		0x09
#define	SKILL_PLAY_GRAND_SMASH		0x0A
#define	SKILL_PLAY_SPARK_SHIELD		0x0B

#define	SKILL_PLAY_IMPULSION		0x0C
#define	SKILL_PLAY_COMPULSION		0x0D
#define	SKILL_PLAY_MAGNETIC_SPHERE	0x0E
#define	SKILL_PLAY_METAL_GOLEM		0x0F


//////////// Pikeman skill //////////////
#define SKILL_PLAY_PIKEWIND			0x12	//Jaewon Park-Modify the assigned code because it was not recognized as the primary skill when using Magic Force (modified to 0x10 -> 0x12)
#define SKILL_PLAY_CRITICAL_HIT		0x13
#define SKILL_PLAY_JUMPING_CRASH	0x14

#define SKILL_PLAY_GROUND_PIKE		0x15
#define SKILL_PLAY_TORNADO			0x16
#define SKILL_PLAY_EXPANSION		0x18

#define SKILL_PLAY_VENOM_SPEAR		0x19

#define SKILL_PLAY_BLADE_OF_BLAZE	0x1A		//(old)
#define SKILL_PLAY_VANISH			0x1A		//same code as SKILL_PLAY_BLADE_OF_BLAZE

#define SKILL_PLAY_CHAIN_LANCE		0x1B

#define SKILL_PLAY_ASSASSIN_EYE		0x1C
#define SKILL_PLAY_CHARGING_STRIKE	0x1D
#define SKILL_PLAY_VAGUE			0x1E
#define SKILL_PLAY_SHADOW_MASTER	0x1F


//////////// Fighter Skill //////////////
#define SKILL_PLAY_RAVING			0x23
#define SKILL_PLAY_IMPACT			0x24

#define SKILL_PLAY_TRIPLE_IMPACT	0x25
#define SKILL_PLAY_BRUTAL_SWING		0x26
#define SKILL_PLAY_ROAR				0x27
#define SKILL_PLAY_RAGEOF_ZECRAM	0x28

#define SKILL_PLAY_CONCENTRATION	0x29
#define SKILL_PLAY_AVANGING_CRASH	0x2A
#define SKILL_PLAY_SWIFT_AXE		0x2B
#define SKILL_PLAY_BONE_SMASH		0x2C

#define SKILL_PLAY_DESTROYER		0x2D
#define SKILL_PLAY_BERSERKER		0x2E
#define SKILL_PLAY_CYCLONE_STRIKE	0x2F

//////////// Archer skill //////////////

#define SKILL_PLAY_SCOUT_HAWK		0x41
#define SKILL_PLAY_WIND_ARROW		0x43
#define SKILL_PLAY_PERFECT_AIM		0x44

#define SKILL_PLAY_FALCON			0x46
#define SKILL_PLAY_ARROWOF_RAGE		0x47
#define SKILL_PLAY_AVALANCHE		0x48

#define SKILL_PLAY_ELEMENTAL_SHOT	0x49
#define SKILL_PLAY_GOLDEN_FALCON	0x4A
#define SKILL_PLAY_BOMB_SHOT		0x4B
#define SKILL_PLAY_PERFORATION		0x4C

#define SKILL_PLAY_RECALL_WOLVERIN	0x4D
#define SKILL_PLAY_PHOENIX_SHOT		0x4E
#define SKILL_PLAY_FORCE_OF_NATURE	0x4F


////////////// Knight Skill //////////////
#define SKILL_PLAY_SWORD_BLAST		0x51
#define SKILL_PLAY_HOLY_BODY		0x52
#define SKILL_PLAY_DOUBLE_CRASH		0x54

#define SKILL_PLAY_HOLY_VALOR		0x55
#define SKILL_PLAY_BRANDISH			0x56
#define SKILL_PLAY_PIERCING			0x57
#define SKILL_PLAY_DRASTIC_SPIRIT	0x58

#define SKILL_PLAY_FLAME_BRANDISH		0x59
#define SKILL_PLAY_DIVINE_INHALATION	0x5A
#define SKILL_PLAY_HOLY_INCANTATION		0x5B
#define SKILL_PLAY_GRAND_CROSS			0x5C

#define SKILL_PLAY_DIVINE_PIERCING		0x5D
#define SKILL_PLAY_GODLY_SHIELD			0x5E
#define SKILL_PLAY_GODS_BLESS			0x5F
#define SKILL_PLAY_SWORD_OF_JUSTICE		0x50


////////////// Atalanta Skill ///////////////
#define SKILL_PLAY_SHIELD_STRIKE	0x61
#define SKILL_PLAY_FARINA			0x62
#define SKILL_PLAY_VIGOR_SPEAR		0x64

#define SKILL_PLAY_WINDY			0x65
#define SKILL_PLAY_TWIST_JAVELIN	0x66
#define SKILL_PLAY_SOUL_SUCKER		0x67
#define SKILL_PLAY_FIRE_JAVELIN		0x68

#define SKILL_PLAY_SPLIT_JAVELIN		0x69
#define SKILL_PLAY_TRIUMPH_OF_VALHALLA	0x6A
#define SKILL_PLAY_LIGHTNING_JAVELIN	0x6B
#define SKILL_PLAY_STORM_JAVELIN		0x6C

#define SKILL_PLAY_HALL_OF_VALHALLA		0x6D
#define SKILL_PLAY_X_RAGE				0x6E
#define SKILL_PLAY_FROST_JAVELIN		0x6F
#define SKILL_PLAY_VENGEANCE			0x60


////////////// Priestis Skill ///////////////
#define SKILL_PLAY_HEALING			0x71
#define SKILL_PLAY_HOLY_BOLT		0x72
#define SKILL_PLAY_MULTI_SPARK		0x73
#define SKILL_PLAY_HOLY_MIND		0x74

//#define	SKILL_PLAY_MEDITATION		0x75
#define	SKILL_PLAY_DIVINE_LIGHTNING	0x76
#define	SKILL_PLAY_HOLY_REFLECTION	0x77
#define	SKILL_PLAY_GREAT_HEALING	0x78

#define	SKILL_PLAY_VIGOR_BALL		0x79
#define	SKILL_PLAY_RESURRECTION		0x7A
#define	SKILL_PLAY_EXTINCTION		0x7B
#define	SKILL_PLAY_VIRTUAL_LIFE		0x7C

#define	SKILL_PLAY_GLACIAL_SPIKE	0x7D
#define	SKILL_PLAY_REGENERATION_FIELD	0x7E
#define	SKILL_PLAY_CHAIN_LIGHTNING	0x7F
#define	SKILL_PLAY_SUMMON_MUSPELL	0x70


////////////// Magician skill ///////////////
#define SKILL_PLAY_AGONY			0x81
#define SKILL_PLAY_FIRE_BOLT		0x82
#define SKILL_PLAY_ZENITH			0x83
#define SKILL_PLAY_FIRE_BALL		0x84

//#define SKILL_PLAY_MENTAL_MASTERY	0x85
#define SKILL_PLAY_COLUMN_OF_WATER	0x86
#define SKILL_PLAY_ENCHANT_WEAPON	0x87
#define SKILL_PLAY_DEAD_RAY			0x88

#define SKILL_PLAY_ENERGY_SHIELD	0x89
#define SKILL_PLAY_DIASTROPHISM		0x8A
#define SKILL_PLAY_SPIRIT_ELEMENTAL	0x8B
#define SKILL_PLAY_DANCING_SWORD	0x8C

#define SKILL_PLAY_FIRE_ELEMENTAL	0x8D
#define SKILL_PLAY_FLAME_WAVE		0x8E
#define SKILL_PLAY_DISTORTION		0x8F
#define SKILL_PLAY_METEO			0x80

///////////// Motion Expansion //////////////////
#define SKILL_PLAY_DIVINE_PIERCING2		0x90
#define SKILL_PLAY_DIVINE_PIERCING3		0x91


#define	smCHAR_STATE_NPC		0    //Is a NPC
#define	smCHAR_STATE_MONSTER	1    //Is a enemy monster
#define	smCHAR_STATE_PLAYER		0x80 //Is a friendly player

#define	smCHAR_MONSTER_NATURAL	0x80
#define	smCHAR_MONSTER_GOOD		0x81
#define	smCHAR_MONSTER_EVIL		0x82

#define	smCHAR_MONSTER_NORMAL	0x00
#define	smCHAR_MONSTER_UNDEAD	0x90
#define	smCHAR_MONSTER_MUTANT	0x91
#define	smCHAR_MONSTER_DEMON	0x92
#define	smCHAR_MONSTER_MECHANIC	0x93

#define	smCHAR_MONSTER_SUMMON		0xA0

#define	smCOMMNAD_USER_WARP		0x100
#define	smCOMMNAD_USER_AGINGUP	0x110
#define	smCOMMNAD_USER_HOLY_INCANTATION	0x120
#define	smCOMMNAD_USER_RESURRECTION	0x130
#define	smCOMMNAD_USER_FORCEORB	0x140
#define	smCOMMNAD_USER_VALENTO	0x150
#define	smCOMMNAD_USER_FIREFLOWER	0x160

#define	smCOMMAND_PLAY_BABEL		0x200
#define	smCOMMAND_PLAY_BELSS_CASTLE	0x210
#define	smCOMMAND_PLAY_PK_FIELD		0x220
#define	smCOMMAND_PLAY_KELVEZU		0x230

#define		SUCCUBUS_CURSE_TIME		10

//40% absorption applied at PK
#define		PKMODE_ABSORB			30


#define CHRMOTION_EXT		10

#define hvPOSI_RHAND	0x0001
#define hvPOSI_LHAND	0x0002


#define CHRMOTION_STATE_STAND		0x40
#define CHRMOTION_STATE_WALK		0x50
#define CHRMOTION_STATE_RUN			0x60
#define CHRMOTION_STATE_FALLDOWN	0x80

#define CHRMOTION_STATE_ATTACK		0x100
#define CHRMOTION_STATE_DAMAGE		0x110
#define CHRMOTION_STATE_DEAD		0x120
#define CHRMOTION_STATE_SOMETIME	0x130
#define CHRMOTION_STATE_POTION		0x140
#define CHRMOTION_STATE_SKILL		0x150

#define CHRMOTION_STATE_FALLSTAND	0x170
#define CHRMOTION_STATE_FALLDAMAGE	0x180

#define CHRMOTION_STATE_RESTART		0x200
#define CHRMOTION_STATE_WARP		0x210

#define CHRMOTION_STATE_YAHOO		0x220

//used only for sound classification
#define CHRMOTION_STATE_HAMMER		0x300


#define CHRMOTION_STATE_TALK_AR			0x400
#define CHRMOTION_STATE_TALK_E			0x410
#define CHRMOTION_STATE_TALK_OH			0x420
#define CHRMOTION_STATE_TALK_EYE		0x430
#define CHRMOTION_STATE_TALK_BLANK		0
#define CHRMOTION_STATE_TALK_SMILE		0x440
#define CHRMOTION_STATE_TALK_GRUMBLE	0x450
#define CHRMOTION_STATE_TALK_SORROW		0x460
#define CHRMOTION_STATE_TALK_STARTLED	0x470
#define CHRMOTION_STATE_TALK_NATURE		0x480
#define CHRMOTION_STATE_TALK_SPECIAL	0x490


//Define the class of weapons
/*---------------------------------------------*
*			(Weapons) Primary Category
*----------------------------------------------*/
#define sinWA1			0x01010000	//Axes
#define sinWC1			0x01020000	//Claws
#define sinWH1			0x01030000	//Hammer & So On
#define sinWM1			0x01040000	//Magicial Stuffs
#define sinWP1			0x01050000	//Poles & Spears
#define sinWS1			0x01060000	//Shooters
#define sinWS2			0x01070000	//Swords
#define sinWT1			0x01080000	//Throwing Arms


/*---------------------------------------------*
* (Armor) 1st category
*----------------------------------------------*/

#define sinDA1			0x02010000	//Armor
#define sinDB1			0x02020000	//Boots
#define sinDG1			0x02030000	//Gloves
#define sinDS1			0x02040000	//Shields
#define sinDA2			0x02050000	//Armor


							/*---------------------------------------------*
							* (Accessories) 1st category
							*----------------------------------------------*/

#define sinOA1			0x03010000	//Amulet
#define sinOA2			0x03020000	//Armlet
#define sinOM1			0x03030000	//Magicial Stuffs
#define sinOR1			0x03040000	//Ring
#define sinOR2			0x03050000	//Ring2
#define sinOS1			0x02350000	//Sheltom
#define sinFO1			0x03060000  //Force Orb
#define sinSE1			0x03070000  //Seel
#define sinPR1			0x03080000  //ore pluto
#define sinPR2			0x03090000  //crystal pluto
#define sinPR3			0x03100000  //Rune (A) pluto
#define sinPR4			0x03110000  //Rune (B) pluto
							/*---------------------------------------------*
							* (Potion) 1st category
							*----------------------------------------------*/
#define sinPM1			0x04010000  //Mana
#define sinPL1			0x04020000  //Life
#define sinPS1			0x04030000  //Stamina

							/*---------------------------------------------*
							* (money) 1st category
							*----------------------------------------------*/
#define sinGG1			0x05010000 //Gold
#define sinBS1			0x05020000 //Bellatostone

							/*---------------------------------------------*
							* (return) 1st category
							*----------------------------------------------*/
#define sinEC1			0x06010000

							/*---------------------------------------------*
							* Quest Item
							*----------------------------------------------*/

#define sinQT1			0x07010000


							/*---------------------------------------------*
							* Event Item
							*----------------------------------------------*/
#define sinSP1			0x08010000
#define sinGP1			0x08020000		//0x09010000, so it's a problem. (& sinITEM_MASK2 doesn't work)
#define sinQW1			0x08030000		//Warpgate Wing
#define sinGF1			0x08040000		//separate gift certificate
#define sinPZ1			0x08060000		//Archer Puzzle
#define sinPZ2			0x08070000		//King Hope Puzzle
#define sinCH1			0x08080000		//Valentine's Day chocolate
#define sinSD2			0x08090000		//Sod2 occurrence item
#define sinBC1          0x080A0000      //Siege warfare occurrence item
#define sinBI1          0x080B0000      //Paid purchase item
#define sinBI2          0x080C0000      //Paid purchase item (package cash item)
#define sinGP2			0x080D0000		//Chapter Bye-Soul Stone


							/*---------------------------------------------*
							*			  Make Item
							*----------------------------------------------*/
#define sinMA1			0x09010000
#define sinMA2			0x09020000


							/*---------------------------------------------*
							* Crafting Material Item
							*----------------------------------------------*/
							//by pluto
#define sinWR1			0x0A010000 //Arms Recipe
#define sinDR1			0x0A020000 //Armor Recipe

#define EXTREME_RECIPE		1		//Forgotten Recipe
#define ANCIENT_RECIPE		2		//Ancient Recipe
#define	MINOTAUR_RECIPE		3		//Earth Recipe
#define DOOM_RECIPE			4		//Dark Recipe
#define SALAMANDER_RECIPE	5		//Hwamyeong's Recipe
#define WYVERN_RECIPE		6		//Wind Recipe
#define PHOENIX_RECIPE		7		//Solar Recipe
#define FRENZY_RECIPE		8		//Dire Recipe
#define HEAVENS_RECIPE		9		//Heavenly Recipe
#define SNOW_RECIPE			10		//Posul's Recipe
#define MEMORY_RECIPE		11		//Recipe of Memory // Chapter Bye-Blacksmith's Soul




#define	PRIME_ITEM_PACKAGE_NONE			0
#define	PRIME_ITEM_PACKAGE_BRONZE		1
#define	PRIME_ITEM_PACKAGE_SILVER		2
#define	PRIME_ITEM_PACKAGE_GOLD			3
#define	PRIME_ITEM_PACKAGE_ULTRA		4

							//pluto Mana Reduce Potion
#define PRIME_ITEM_MIGHTOFAWELL			5
#define PRIME_ITEM_MANAREDUCE			6


							//SOD related
#define	rsSOD_FIELD			30
#define	rsSOD_VILLAGE		9
#define	rsBABEL_FIELD		27
#define	rsKELVEZU_FIELD		36
#define	rsMOKOVA_FIELD		38
							//Siege
#define	rsCASTLE_FIELD	33
#define	rsACTION_FIELD	39

							//Quest Battle Arena
#define	QUEST_ARENA_FIELD		32
#define	QUEST_ARENA_NPC_POS_X	(22091*fONE)
#define	QUEST_ARENA_NPC_POS_Z	(9673*fONE)


#define	WHERE_TRADE				300
#define	WHERE_GIFT_EXPRESS		600
#define	WHERE_AGINGITEM			400
#define	WHERE_CRAFTITEM			420
#define	WHERE_FORECORB			440
#define	WHERE_LEARNSKILL		460
#define	WHERE_WARPGATE			470
#define	WHERE_BUY_ITEM			200
#define	WHERE_BUY_POTION		210
#define	WHERE_SELL_ITEM			220
#define	WHERE_LOAD_PLAYER		100
#define	WHERE_THROW_ITEM		120
#define	WHERE_GET_ITEM			130
#define	WHERE_STAR_POINT		620
#define	WHERE_CLAN_MONEY		630
#define	WHERE_GIVE_MONEY		640
#define	WHERE_PERSONAL_SHOP		320
#define	WHERE_OPEN_WAREHOUES	500


#define STG_START_POINT_MAX			200



/////Type of quest
#define HAQUEST_CODE_ELEMENTARY_A		0x0020
#define HAQUEST_CODE_ELEMENTARY_B	    0x0021
#define HAQUEST_CODE_ELEMENTARY_C	    0x0022
#define HAQUEST_CODE_ELEMENTARY_D   	0x0023
#define HAQUEST_CODE_ELEMENTARY_E   	0x0024
#define HAQUEST_CODE_ELEMENTARY_F		0x0025
#define HAQUEST_CODE_ELEMENTARY_G		0x0026
#define HAQUEST_CODE_ELEMENTARY_X		0x0027
//Fury of phantom
#define HAQUEST_CODE_FURYOFPHANTOM      0x0028





/////Type of quest
#define SIN_QUEST_CODE_CHANGEJOB		0x0001
#define SIN_QUEST_CODE_CHANGEJOB2_NPC_M	0x0002
#define SIN_QUEST_CODE_CHANGEJOB2_NPC_D	0x0003
#define SIN_QUEST_CODE_CHANGEJOB3   	0x0004
#define SIN_QUEST_CODE_CHANGEJOB4   	0x0010

//Level Quest
#define SIN_QUEST_CODE_LEVEL30			0x0005
#define SIN_QUEST_CODE_LEVEL55			0x0006
#define SIN_QUEST_CODE_LEVEL55_2		0x0007
#define SIN_QUEST_CODE_LEVEL70			0x0008
#define SIN_QUEST_CODE_LEVEL80			0x0009
#define SIN_QUEST_CODE_LEVEL85			0x000A
#define SIN_QUEST_CODE_LEVEL90			0x000B


#define SIN_QUEST_CODE_LEVEL80_2		0x000C //Linked quest is an additional quest
#define SIN_QUEST_CODE_LEVEL90_2		0x000D //Linked quest is an additional quest


							/////Quest progress
#define SIN_QUEST_PROGRESS				1
#define SIN_QUEST_COMPLETE				2


#define	SIN_SOUND_AXES				1
#define	SIN_SOUND_CLAWS				2
#define	SIN_SOUND_HAMMER			3
#define	SIN_SOUND_MAGICIAL		 	4
#define	SIN_SOUND_POLES				5
#define	SIN_SOUND_SHOOTERS			6
#define	SIN_SOUND_SWORDS			7
#define	SIN_SOUND_THROWING			8
#define	SIN_SOUND_ARMOR				9
#define	SIN_SOUND_BOOTS				10
#define	SIN_SOUND_GLOVES			11
#define	SIN_SOUND_SHIELDS			12
#define	SIN_SOUND_AMULET			13
#define	SIN_SOUND_Armlet			14
#define	SIN_SOUND_RING				15
#define SIN_SOUND_SHELTOM			16
#define SIN_SOUND_POTION			17
#define SIN_SOUND_COIN				18
#define SIN_SOUND_STAFF				19
#define	SIN_SOUND_EAT_POTION		20
#define	SIN_SOUND_SHOW_INTER		21
#define	SIN_SOUND_REPAIR_ITEM		22
#define	SIN_SOUND_FAILD_MIXITEM		23
#define	SIN_SOUND_ARMOR2			24
#define	SIN_SOUND_EAT_POTION2		25



//////////////////////////////// other skills
#define	GROUP_OTHERSKILL		0x09000000

////////////////////////////// full-time CODE
#define	CHANGE_JOB1				0x00010000
#define	CHANGE_JOB2				0x00020000
#define	CHANGE_JOB3				0x00040000
#define	CHANGE_JOB4				0x00080000

////////////////////////////// skill detail code
#define SKILL_1					0x00000001
#define SKILL_2					0x00000002
#define SKILL_3					0x00000003
#define SKILL_4					0x00000004
#define SKILL_5					0x00000005
#define SKILL_6					0x00000006
#define SKILL_7					0x00000007
#define SKILL_8					0x00000008
#define SKILL_9					0x00000009
#define SKILL_10				0x00000010

#define	GROUP_OTHERSKILL		0x09000000

#define SKILL_FORCE_ORB			(GROUP_OTHERSKILL | CHANGE_JOB1 | SKILL_1)

#define CHANGE_JOB3_QUEST		(GROUP_OTHERSKILL | CHANGE_JOB1 | SKILL_2)
#define CHANGE_ELEMENTARY_QUEST	(GROUP_OTHERSKILL | CHANGE_JOB1 | SKILL_3)


#define	ENCHANT_WEAPON					80
#define ENCHANT_WEAPON_FIRE				100
#define ENCHANT_WEAPON_ICE				200
#define ENCHANT_WEAPON_LIGHT			300
#define ENCHANT_MEMBER_JIN				400
#define IMPULSION_LIGHT                 500

#define HOLY_ACTION						700
#define DRASTIC_ACTION					750
#define HOLY_VALOR_JANG					800
#define HOLY_VALOR_MEMBER				900
#define DRASTIC_SPIRIT_JANG				1000
#define DRASTIC_SPIRIT_MEMBER			1100
#define WINDY_ACTION					1200
#define HOLY_MIND_ATTACK				1300

#define STOP_PART_FLAG					1399
#define AGING_BODY						1400
#define FURY_EYE1						1401
#define CLAN_MONSTER_PART1				1402
#define PIGON_HAND_FIRE					1403
#define CLASS_UP_PART1					1404
#define IRON_MONSTER_CHAINGOLEM1		1405

#define IRON_MONSTER_RUNIC_GUARDIAN_HAND1 1406
#define SHELLTOM_WEAPON					  1407

#define ICE_MONSTER_CHAOSKARA_STAFF		1408
#define ICE_MONSTER_VALENTO_BODY		1409
#define MONSTER_SPIDERTROOPER			1410
#define EFFECT_FIRECRACKER				1411
#define MONSTER_KELVEZU_CIRCLE			1412


#define ANGLE_360				4096
#define ITEM_TRANS_LIMIT_TIME	16000
#define ANGLE_90				(ANGLE_360/4)


#define   SIN_ADD_FIRE				0x00000001	//Llama
#define   SIN_ADD_ICE				0x00000002	//Escarcha
#define   SIN_ADD_LIGHTNING			0x00000004	//Rayo
#define   SIN_ADD_POISON			0x00000008	//Veneno
#define   SIN_ADD_BIO				0x00000010	//Org?ico
#define   SIN_ADD_CRITICAL			0x00000020	//Cr?ico
#define   SIN_ADD_ATTACK_RATE		0x00000040	//Capacidad de Ataque
#define   SIN_ADD_DAMAGE_MIN		0x00000080	//M?imo Poder de Ataque
#define   SIN_ADD_DAMAGE_MAX		0x00000100	//M?imo Poder de Ataque
#define   SIN_ADD_ATTACK_SPEED		0x00000200	//Velocidad de Ataque
#define   SIN_ADD_ABSORB			0x00000400	//Capacidad de Absorci?
#define   SIN_ADD_DEFENCE			0x00000800	//Capacidad deDefensa
#define   SIN_ADD_BLOCK_RATE		0x00001000	//Capacidad de Bloqueo
#define   SIN_ADD_MOVE_SPEED		0x00002000	//Velocidad de Movimiento
#define   SIN_ADD_LIFE				0x00004000	//M?imo HP
#define   SIN_ADD_MANA				0x00008000	//M?imo MP
#define   SIN_ADD_STAMINA			0x00010000	//M?imo STM
#define   SIN_ADD_LIFEREGEN			0x00020000 	//Vida Regen.
#define   SIN_ADD_MANAREGEN			0x00040000  //Mana Regen.
#define   SIN_ADD_STAMINAREGEN		0x00080000  //Vigor Regen.